travis:
  secure:
    BINSTAR_TOKEN: Ot6v5OKx1NVl0h8134nCJ2NFppnth01T2Em9cf4blNHSPlXsFyJtONdbgkgTPG5OQ3R+srLo2OZx6paeW98ql5SAwNZqTO5aaCQnnzqXKSCAU3Cq41+8btFZj4vhIXVRW/nWmiNNrNLC8SwHpIZgUVfVgTKSXMsuiq7wQlcCmmUXmlpXSq9X9VJVj6RkiI1C1Zs4fko5pyqiKZNDwX3aoTtS7Eb8BWrTU3DsLyCndPR8HBhVPbIXvmHlgkdD+ns/AUk85/DiHTmXpEzGM/SZveRkVzLxHMopnKFfzkP7Q7rzEU8Yh/9GhxVOs7iOSNUPPEzS5PBEx/l6+I1bIj8qHGs0/k8bXXW1A2IK1MBTh27GspSKBH/4kAfbLXbQ+6GaKcJw+rNNQOmjoft+F3Dodwywf6qEdmkSEIeSHkDn5VeF6anqMZ6UySRAw3xtKyRDik/o+VJkHdVfW3DdefqhgjeVs41eAk+BhIwqwvxwjb0jk1ees9FSfCOXu4Bv+1jQkjNseoq6mlPN3Wu62JACPx5C+XsT/G3jreMYm6IRTEU9t+j/KS7rn4hcaoA76GYdVkDeJ3mdJLKisGP7RKWQB15k5bHOnavQFK20ebOjpo3VrhynBNfDnUxSkwpSwpdDBMRw95tJFV1CWCzUmdF2IEvplaoCk9bO0vXcdhi1HA4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
